### ISSUE TITLE
새로운 채팅방에 join 되지 않습니다. 

### ISSUE THREAD

**Issue by hcsworld** [hcsworld/PS_chat#2]
**Describe the bug**
main page에서 채팅방 입장코드를 입력 후 join button을 눌러도 해당 채팅방에 입장되지 않습니다.

**To Reproduce**
1. 로그인 후 mainpage 접속
2. 참가코드를 입력후 join 버튼 클릭
3. 존재하는 채팅방 코드인데 참여가 안된다는 에러메세지 alert

**Expected behavior**
채팅방의 정보가 server에 저장되는 데에 있어 문제가 발생한 것 같습니다. 

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 16.1

**Additional context**

**Comment by dlwns147** [comment]
server branch에서 3be8a13d18cad0b48eade6c0d1e416f80ff6f611 commit에서 수정하였습니다.

 감사합니다
